cherrypy:
  server:
    socket_timeout: 75

plugins:
  uber:
    path: 'uber'
    api_enabled: true

    sqlalchemy_pool_size: 5
    sqlalchemy_max_overflow: 10

    code_of_conduct_url: 'http://super.magfest.org/codeofconduct'
    consent_form_url: 'http://super.magfest.org/parentalconsentform'
    contact_url: 'http://super.magfest.org/contact'
    prereg_faq_url: 'http://super.magfest.org/faq'
    privacy_policy_url: 'https://super.magfest.org/privacy-policy'
    jira_enabled: true
    attendee_accounts_enabled: false
    maps_enabled: false
    maps_dir: /tmp
    blank_staff_badges: 50
    kiosk_cc_enabled: true

    panels_twilio_number: '+12405415595'
    tabletop_twilio_number: '+15713646627'

    preassigned_badge_types: ['staff_badge','contractor_badge']

    admin_email: MAGFest Sys Admin <sysadmin@magfest.org>
    developer_email: MAGFest Software <developers@magfest.org>
    security_email: MAGFest Security <security@magfest.org>

    regdesk_email: MAGFest Registration <regsupport@magfest.org>
    regdesk_email_signature: '- MAGFest Registration Department'

    staff_email: MAGFest Staffing <stops@magfest.org>
    stops_email_signature: '- MAGFest Staff Operations'

    marketplace_email: MAGFest Marketplace <marketplace@magfest.org>
    marketplace_email_signature: '- MAGFest Marketplace'

    panels_email: MAGFest Panels <panels@magfest.org>
    panels_email_signature: '- MAGFest Panels Department'

    guest_email: MAGFest Guests <guests@magfest.org>
    guest_email_signature: '- MAGFest Guest Department'

    band_email: MAGFest Music Department <music@magfest.org>
    band_email_signature: '- MAGFest Music Department'

    prereg_hotel_info_email_sender: Do Not Reply <noreply@magfest.org>
    prereg_hotel_info_email_signature: '- MAGFest'

    secret:
      barcode_key: 'TEST ONLY!'
      barcode_salt: 255
      barcode_event_id: 255
